name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Display the path
        run: echo %PATH%
        shell: cmd
      - name: test
        run: make
        working-directory: ./Lab1
        shell: cmd
